version: '4.41.2'

services:
  api-financas-em-dia:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api